---
- name: first play
  hosts: all
  tasks: 
    - name: create a new file
      file:
        path: /tmp/foo.conf
        mode: 0664
        owner: ansible
        state: touch
      tags: file_touch
    - name: create groups
      import_tasks: group-tasks.yml
      tags: grp
