---
- name: first play
  hosts: all
  tasks:
    - name: install tmux
      package:
        name: tmux
        state: present

    - name: archive /var/log
      archive:
        path: /var/log
        dest: /tmp/logs.tar.gz
        format: gz

- name: second play
  hosts: slave1
  tasks:
    - name: install git
      yum:
        name: git
        state: present
      tags: git
